### ISSUE TITLE
Add QR code to the UI cards

### ISSUE THREAD

**Issue by bprussell** [e-gineering/urlshortener#11]
Add an element to the cards in the UI that allows the user to display and/or download the QR code for the short URL by calling the `/api/qr/{url}` endpoint that was added on #9.

**Comment by timmiller17** [comment]
Is this the same as adding a card to the UI that has an input field where you can input some text (such as a website URL) and have it be converted to a URLEncoded version and get back a QR code or have it be downloaded like it is with the API currently?

I just want to type in a box and hit a button and get a QR code.

**Comment by bprussell** [comment]
I would say the Add functionality would fall more under issue #3 . This issue was intended as an enhancement to the View functionality on the existing cards.
